name: Python Master Workflow
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


# https://github.com/executablebooks/jupyter-book/issues/510
# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    name: Book Workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r test/requirements.txt

    # Build the book
    - name: Build
      run: |
        jupyter-book build test
    
    # Push the book's HTML to github-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: test/_build/html

